{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_release",
    "version": "1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.10.aar",
          "url": "ekyc_flutter_sdk_release-1.10.aar",
          "size": 8140728,
          "sha512": "575e45d9b881a65d887955af853f3e69bc542b5b051e6c4b27ea62d32b4e4011078726ee30697cc7e42dcf274983a34682d2a81f30b0fa157c548a0edf80fe08",
          "sha256": "15e1967fd15886cebf171fa934e3d139e0ff90a943c06a588deebf8aa9b1cda3",
          "sha1": "ed9a71765e6d609414d66417d044db09179c6907",
          "md5": "0a7d51c25d26fd5f0a5cfffb4c11211a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.10.aar",
          "url": "ekyc_flutter_sdk_release-1.10.aar",
          "size": 8140728,
          "sha512": "575e45d9b881a65d887955af853f3e69bc542b5b051e6c4b27ea62d32b4e4011078726ee30697cc7e42dcf274983a34682d2a81f30b0fa157c548a0edf80fe08",
          "sha256": "15e1967fd15886cebf171fa934e3d139e0ff90a943c06a588deebf8aa9b1cda3",
          "sha1": "ed9a71765e6d609414d66417d044db09179c6907",
          "md5": "0a7d51c25d26fd5f0a5cfffb4c11211a"
        }
      ]
    }
  ]
}
