{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 22065,
          "sha512": "3acb1a1669916a7d0f332baf928219d6f89bfdd8241f7f29668e0c1d98dbdc7074b10e2342eafb236329dbeedde4f45f8046e417747dc3a5cf994c35e88905f1",
          "sha256": "1abf7165d1573b839dd6a18c6c770a33b2c6f47481221c569fd1c7deba8623f2",
          "sha1": "6e831f5154ace20e664b3380c069cedb16da0172",
          "md5": "4f1eec0197db44e6baf0027964365691"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 22065,
          "sha512": "3acb1a1669916a7d0f332baf928219d6f89bfdd8241f7f29668e0c1d98dbdc7074b10e2342eafb236329dbeedde4f45f8046e417747dc3a5cf994c35e88905f1",
          "sha256": "1abf7165d1573b839dd6a18c6c770a33b2c6f47481221c569fd1c7deba8623f2",
          "sha1": "6e831f5154ace20e664b3380c069cedb16da0172",
          "md5": "4f1eec0197db44e6baf0027964365691"
        }
      ]
    }
  ]
}
