{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-release_28_oct_2023_v4.aar",
          "url": "flutter_plugin_android_lifecycle_release-release_28_oct_2023_v4.aar",
          "size": 4630,
          "sha512": "bf13705ba378caee2597ebed23e5a28ef6f54e2e05e0b38604f2f0f227253a4edddf719a2d44a268224aa7579460fcd853dee49dc2d1476055b6c9e5149e4e18",
          "sha256": "72913e71e9d77296e792cfe2caf68dabb1b6058567d606137dfac8c3a2f4416d",
          "sha1": "ad2ef9a19c4e8b7d1840e2368a960a9e6cb59018",
          "md5": "17383a7e4ac05b5cd5aecf7b6018e142"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-release_28_oct_2023_v4.aar",
          "url": "flutter_plugin_android_lifecycle_release-release_28_oct_2023_v4.aar",
          "size": 4630,
          "sha512": "bf13705ba378caee2597ebed23e5a28ef6f54e2e05e0b38604f2f0f227253a4edddf719a2d44a268224aa7579460fcd853dee49dc2d1476055b6c9e5149e4e18",
          "sha256": "72913e71e9d77296e792cfe2caf68dabb1b6058567d606137dfac8c3a2f4416d",
          "sha1": "ad2ef9a19c4e8b7d1840e2368a960a9e6cb59018",
          "md5": "17383a7e4ac05b5cd5aecf7b6018e142"
        }
      ]
    }
  ]
}
