{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 22323,
          "sha512": "b82e91878a1c775da1548a38f97f5213ea47b45c62277102b195496735369c2aefd71815c5c0e539627718f70f3a0e5da8d3e36d1a2be47ac28dde70eec976bf",
          "sha256": "c885d7ef6339ac6fae8df19793d8a55e063530e4ff8763ba6db485ad66ff61f9",
          "sha1": "5394755c9007d1b5296a57b5b9e0788581febcb2",
          "md5": "50e5513cfcced4deeb6f9c206f699601"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 22323,
          "sha512": "b82e91878a1c775da1548a38f97f5213ea47b45c62277102b195496735369c2aefd71815c5c0e539627718f70f3a0e5da8d3e36d1a2be47ac28dde70eec976bf",
          "sha256": "c885d7ef6339ac6fae8df19793d8a55e063530e4ff8763ba6db485ad66ff61f9",
          "sha1": "5394755c9007d1b5296a57b5b9e0788581febcb2",
          "md5": "50e5513cfcced4deeb6f9c206f699601"
        }
      ]
    }
  ]
}
