{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-release_28_oct_2023_v4.aar",
          "url": "url_launcher_android_debug-release_28_oct_2023_v4.aar",
          "size": 22369,
          "sha512": "0ce2bf241009e05d7b7e44cc92fce8538cd9ad84a4a28e46205559337a100aa12261c544ea340d243877c450215da8c516315472d659c59c6cfde6ebf47618c9",
          "sha256": "8b62f5e1b9271c1be89cb57248e674b8d55759519b5f4908b5e3214dcff04e0c",
          "sha1": "8bc2d806f389f9eb77c9ae0d7e112cc9c647ba0e",
          "md5": "fb18e504806e392fe98baab3776b7c6d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-release_28_oct_2023_v4.aar",
          "url": "url_launcher_android_debug-release_28_oct_2023_v4.aar",
          "size": 22369,
          "sha512": "0ce2bf241009e05d7b7e44cc92fce8538cd9ad84a4a28e46205559337a100aa12261c544ea340d243877c450215da8c516315472d659c59c6cfde6ebf47618c9",
          "sha256": "8b62f5e1b9271c1be89cb57248e674b8d55759519b5f4908b5e3214dcff04e0c",
          "sha1": "8bc2d806f389f9eb77c9ae0d7e112cc9c647ba0e",
          "md5": "fb18e504806e392fe98baab3776b7c6d"
        }
      ]
    }
  ]
}
