{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_release",
    "version": "1.9.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.9.18.aar",
          "url": "trust_vision_plugin_release-1.9.18.aar",
          "size": 70930,
          "sha512": "eef3000bb2decbc3ff89e6f0f922e1cbb878e1ba51deb2c0f2980d0cc22af658368e1ddad2dcc32bd93a87977a339df7e4d6db126aeb498595ba01c0a503135a",
          "sha256": "0d54f175229760a3a261fab1fcbf9420819535cf79fe1b79314b5bf1b756bae1",
          "sha1": "75364862fea70153cf08f427a495703f9e4f484b",
          "md5": "2b076f380ced8a3d661e372ad9ad6f86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.9.18.aar",
          "url": "trust_vision_plugin_release-1.9.18.aar",
          "size": 70930,
          "sha512": "eef3000bb2decbc3ff89e6f0f922e1cbb878e1ba51deb2c0f2980d0cc22af658368e1ddad2dcc32bd93a87977a339df7e4d6db126aeb498595ba01c0a503135a",
          "sha256": "0d54f175229760a3a261fab1fcbf9420819535cf79fe1b79314b5bf1b756bae1",
          "sha1": "75364862fea70153cf08f427a495703f9e4f484b",
          "md5": "2b076f380ced8a3d661e372ad9ad6f86"
        }
      ]
    }
  ]
}
