{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_debug",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.9.aar",
          "url": "trust_vision_plugin_debug-1.9.aar",
          "size": 76238,
          "sha512": "bdd3900414706d5347a2bf335c2dbd77661e3acb6bd2bdbc61571e1b549f25cac649f26434f3b0ca6abd94fda9e6af37a31e9df9ed1e9944e8373c74eef7e68c",
          "sha256": "1ab9780f906d95db25e9dbbfe063d62afe6083b8c51fb9447ae0af716b7d8dec",
          "sha1": "744202e8ed6faed49e99c73004070289140b4fb1",
          "md5": "71a4aca1dfca4c07ad6e31dcd48db152"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.9.aar",
          "url": "trust_vision_plugin_debug-1.9.aar",
          "size": 76238,
          "sha512": "bdd3900414706d5347a2bf335c2dbd77661e3acb6bd2bdbc61571e1b549f25cac649f26434f3b0ca6abd94fda9e6af37a31e9df9ed1e9944e8373c74eef7e68c",
          "sha256": "1ab9780f906d95db25e9dbbfe063d62afe6083b8c51fb9447ae0af716b7d8dec",
          "sha1": "744202e8ed6faed49e99c73004070289140b4fb1",
          "md5": "71a4aca1dfca4c07ad6e31dcd48db152"
        }
      ]
    }
  ]
}
