{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_release",
    "version": "1.9.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.9.26"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.26.aar",
          "url": "flutter_release-1.9.26.aar",
          "size": 18624187,
          "sha512": "4adca774a2227274b9a5a3b84935bb2bd6ee9b0cc95f8d69a6f844b5f5fa7e55ad3d8c99693786b957d9ade75457fced7305312e91083d6a457452a547c969b3",
          "sha256": "e66a2a597b3cc5f579bbf9ca2a02abb52340ece775bc362da0cb8f57e6c1fca0",
          "sha1": "5399adcb0e8fc59002a1224fed7917bdfbf13a95",
          "md5": "3b33914289d645cdec24f8392d6f9112"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.9.26"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.9.26"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.26.aar",
          "url": "flutter_release-1.9.26.aar",
          "size": 18624187,
          "sha512": "4adca774a2227274b9a5a3b84935bb2bd6ee9b0cc95f8d69a6f844b5f5fa7e55ad3d8c99693786b957d9ade75457fced7305312e91083d6a457452a547c969b3",
          "sha256": "e66a2a597b3cc5f579bbf9ca2a02abb52340ece775bc362da0cb8f57e6c1fca0",
          "sha1": "5399adcb0e8fc59002a1224fed7917bdfbf13a95",
          "md5": "3b33914289d645cdec24f8392d6f9112"
        }
      ]
    }
  ]
}
