{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "size": 4804,
          "sha512": "bccb6ea4d95fc4719237cf02344731a750ea25766a96a26442a1987fe74e9afa49e4ee6c8706712cfec7b399e70b2347a835caec7ecbe80a9534370cbba6e951",
          "sha256": "dc50431286b727b221d28abb0fc404f0340ff6ca6070a485d36f39bb3b17295d",
          "sha1": "97ef787e22330669d35d8f01300d602d5b6aa192",
          "md5": "34b220ad5cb973970eaa621c8d3f76d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "size": 4804,
          "sha512": "bccb6ea4d95fc4719237cf02344731a750ea25766a96a26442a1987fe74e9afa49e4ee6c8706712cfec7b399e70b2347a835caec7ecbe80a9534370cbba6e951",
          "sha256": "dc50431286b727b221d28abb0fc404f0340ff6ca6070a485d36f39bb3b17295d",
          "sha1": "97ef787e22330669d35d8f01300d602d5b6aa192",
          "md5": "34b220ad5cb973970eaa621c8d3f76d8"
        }
      ]
    }
  ]
}
