{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.9.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.9.18.aar",
          "url": "path_provider_android_release-1.9.18.aar",
          "size": 12761,
          "sha512": "38f8a7501027386e2adf509eea99fdd551bdec7cb34e7ff7858d319aa3534dc9bbd29acaa31a23e2262f9313522abdbd9781db72d96ec9828d8c683360df414b",
          "sha256": "f2704bb4e7043598e5eaffcb12309554b5542cc869ee7f3f8e82a45b760de114",
          "sha1": "949a11aca4c75152aee059611a77264cce2fe661",
          "md5": "99cbdb0023202c8454c4aaed5f3de2b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.9.18.aar",
          "url": "path_provider_android_release-1.9.18.aar",
          "size": 12761,
          "sha512": "38f8a7501027386e2adf509eea99fdd551bdec7cb34e7ff7858d319aa3534dc9bbd29acaa31a23e2262f9313522abdbd9781db72d96ec9828d8c683360df414b",
          "sha256": "f2704bb4e7043598e5eaffcb12309554b5542cc869ee7f3f8e82a45b760de114",
          "sha1": "949a11aca4c75152aee059611a77264cce2fe661",
          "md5": "99cbdb0023202c8454c4aaed5f3de2b0"
        }
      ]
    }
  ]
}
