{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.florent37.assetsaudioplayer",
    "module": "assets_audio_player_debug",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "assets_audio_player_debug-release_28_oct_2023_v4.aar",
          "url": "assets_audio_player_debug-release_28_oct_2023_v4.aar",
          "size": 200037,
          "sha512": "8fd26430647823c4e12d04e7bf1da474b700fc95ac618d6e56f42c7a301526eef47d49a542944a01cc0dc4a34fe1b713b6e25364d109837b752f6b735b07c3cb",
          "sha256": "8999077c2b3045814204a1cedf69702c9aaf348fc93263f44fda877ab34c0286",
          "sha1": "91388ba853191061eeae58b39603ab0d3517000f",
          "md5": "817630c495923e8880b67172c17f02bf"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "assets_audio_player_debug-release_28_oct_2023_v4.aar",
          "url": "assets_audio_player_debug-release_28_oct_2023_v4.aar",
          "size": 200037,
          "sha512": "8fd26430647823c4e12d04e7bf1da474b700fc95ac618d6e56f42c7a301526eef47d49a542944a01cc0dc4a34fe1b713b6e25364d109837b752f6b735b07c3cb",
          "sha256": "8999077c2b3045814204a1cedf69702c9aaf348fc93263f44fda877ab34c0286",
          "sha1": "91388ba853191061eeae58b39603ab0d3517000f",
          "md5": "817630c495923e8880b67172c17f02bf"
        }
      ]
    }
  ]
}
