{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_release",
    "version": "1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.11.aar",
          "url": "ekyc_flutter_sdk_release-1.11.aar",
          "size": 8140732,
          "sha512": "2a6f2702b440d92c87656d8627c0f5d281f83a0167c70e792e97b4fcf60855d30aae04447ec908a9b192c859cc7c8f4f89f715f8dc35f8138e84d392af95d0b1",
          "sha256": "2ebdd687d75148325d8beace179611d15ead800f32fdea021678f9f50ef0fd81",
          "sha1": "08e2d405855ed27c9140195b0868fa474be8a6d9",
          "md5": "ac161f246a8afc8f60d6f7ead6c3afa2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.11"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.11.aar",
          "url": "ekyc_flutter_sdk_release-1.11.aar",
          "size": 8140732,
          "sha512": "2a6f2702b440d92c87656d8627c0f5d281f83a0167c70e792e97b4fcf60855d30aae04447ec908a9b192c859cc7c8f4f89f715f8dc35f8138e84d392af95d0b1",
          "sha256": "2ebdd687d75148325d8beace179611d15ead800f32fdea021678f9f50ef0fd81",
          "sha1": "08e2d405855ed27c9140195b0868fa474be8a6d9",
          "md5": "ac161f246a8afc8f60d6f7ead6c3afa2"
        }
      ]
    }
  ]
}
