{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_release",
    "version": "1.9.20-inapp",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.9.20-inapp.aar",
          "url": "trust_vision_plugin_release-1.9.20-inapp.aar",
          "size": 70917,
          "sha512": "34a420670bad484e891ffa67636d94521ace340476339ee7664297df10c4818b75cfe8b21cfcad2d5f380a38d7093b3b9c1a1cd00ffea7530b51126678f01b6a",
          "sha256": "2e4641ee3117d2b2497e200b349f8599e06ad05916ad725aa345f65c46aa7dee",
          "sha1": "94933b7460beeb916e0532ecb026caf79c7bfbeb",
          "md5": "b463ad7d6bd0159601d0bbec38a89d4f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.9.20-inapp.aar",
          "url": "trust_vision_plugin_release-1.9.20-inapp.aar",
          "size": 70917,
          "sha512": "34a420670bad484e891ffa67636d94521ace340476339ee7664297df10c4818b75cfe8b21cfcad2d5f380a38d7093b3b9c1a1cd00ffea7530b51126678f01b6a",
          "sha256": "2e4641ee3117d2b2497e200b349f8599e06ad05916ad725aa345f65c46aa7dee",
          "sha1": "94933b7460beeb916e0532ecb026caf79c7bfbeb",
          "md5": "b463ad7d6bd0159601d0bbec38a89d4f"
        }
      ]
    }
  ]
}
