{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.1.aar",
          "url": "url_launcher_android_debug-1.1.aar",
          "size": 22587,
          "sha512": "e4cca492bf8293f1f0dfbd1e14cad57fa77ecb8db929be01c8eb97461eac9a8a404fc839ed67dcd65c8c319c80b8f1846e8b206d906c1a340a527a06816ded67",
          "sha256": "2441d4b7941087a810ceb23751a1a7fa8a6ac3db0486b3676e81e6a2ef9f28e6",
          "sha1": "f1c0f9d6e71693fbded0c73c3b2e8681c1595526",
          "md5": "7562cb50f598d4d86879764ef34c1987"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.1.aar",
          "url": "url_launcher_android_debug-1.1.aar",
          "size": 22587,
          "sha512": "e4cca492bf8293f1f0dfbd1e14cad57fa77ecb8db929be01c8eb97461eac9a8a404fc839ed67dcd65c8c319c80b8f1846e8b206d906c1a340a527a06816ded67",
          "sha256": "2441d4b7941087a810ceb23751a1a7fa8a6ac3db0486b3676e81e6a2ef9f28e6",
          "sha1": "f1c0f9d6e71693fbded0c73c3b2e8681c1595526",
          "md5": "7562cb50f598d4d86879764ef34c1987"
        }
      ]
    }
  ]
}
