{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linkid.flutter_linkid_digitalfootprint",
    "module": "flutter_linkid_digitalfootprint_debug",
    "version": "1.9.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_linkid_digitalfootprint_debug-1.9.19.aar",
          "url": "flutter_linkid_digitalfootprint_debug-1.9.19.aar",
          "size": 5820,
          "sha512": "501d92fd34fe50c9d6c0a58a18bf942be7a7102097ca560cbfaa89307b7308a56e228aea9694ab7397072b90e9765436c327e5a7c521c0b4d7ad86d00530aa41",
          "sha256": "295f661075e4202925d813fd93e57258b4148d65dd18eb29f56fa552ad17ef22",
          "sha1": "b5115d1776324dda48ec83a8041ab62127e2f906",
          "md5": "4a46b4b0661c81f71c5fccf9eab73348"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "com.linkid.digitalfootprint",
          "module": "linkid-digitalfootprint",
          "version": {
            "requires": "1.0.21"
          }
        },
        {
          "group": "fr.bmartel",
          "module": "jspeedtest",
          "version": {
            "requires": "1.32.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_linkid_digitalfootprint_debug-1.9.19.aar",
          "url": "flutter_linkid_digitalfootprint_debug-1.9.19.aar",
          "size": 5820,
          "sha512": "501d92fd34fe50c9d6c0a58a18bf942be7a7102097ca560cbfaa89307b7308a56e228aea9694ab7397072b90e9765436c327e5a7c521c0b4d7ad86d00530aa41",
          "sha256": "295f661075e4202925d813fd93e57258b4148d65dd18eb29f56fa552ad17ef22",
          "sha1": "b5115d1776324dda48ec83a8041ab62127e2f906",
          "md5": "4a46b4b0661c81f71c5fccf9eab73348"
        }
      ]
    }
  ]
}
