{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.9.27-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.9.27-pre.aar",
          "url": "url_launcher_android_debug-1.9.27-pre.aar",
          "size": 24493,
          "sha512": "0ebcc3e5cf9ac48b469fdebfdeba46141de5ea2d5f197752f34b6de954dc0a29388e4d26ed4aed06cbf49783360fa9509c6a7580d38ce12ae3320a5754d5fd5c",
          "sha256": "f1d026e1603b382b8a2e5ccf5b2b480325d1de53b05a087663f309dbf6a58239",
          "sha1": "73796b91421e8e9a4d790865ca49189ad15dfc45",
          "md5": "efdb6166be73aa06d8970e445ddf10ab"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.9.27-pre.aar",
          "url": "url_launcher_android_debug-1.9.27-pre.aar",
          "size": 24493,
          "sha512": "0ebcc3e5cf9ac48b469fdebfdeba46141de5ea2d5f197752f34b6de954dc0a29388e4d26ed4aed06cbf49783360fa9509c6a7580d38ce12ae3320a5754d5fd5c",
          "sha256": "f1d026e1603b382b8a2e5ccf5b2b480325d1de53b05a087663f309dbf6a58239",
          "sha1": "73796b91421e8e9a4d790865ca49189ad15dfc45",
          "md5": "efdb6166be73aa06d8970e445ddf10ab"
        }
      ]
    }
  ]
}
