{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-release_28_oct_2023_v4.aar",
          "url": "share_plus_debug-release_28_oct_2023_v4.aar",
          "size": 22134,
          "sha512": "9f67880c1b7aef15d95f9033cb0715fe73dd7d4ab7a535ca05df0eb2d2826a4819a806294401633b8f82d3b420f63f2c9999e2d5b8c216d4f751e7e91c0a0d6d",
          "sha256": "1eef57a0daf128fd9a236af482e1b78263e344b81a655e075361911a815936b4",
          "sha1": "4818c9569e83e6dff50a1ab0f1d1519ea78777da",
          "md5": "09d8595c82f413260ec0cbebfb2e7601"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-release_28_oct_2023_v4.aar",
          "url": "share_plus_debug-release_28_oct_2023_v4.aar",
          "size": 22134,
          "sha512": "9f67880c1b7aef15d95f9033cb0715fe73dd7d4ab7a535ca05df0eb2d2826a4819a806294401633b8f82d3b420f63f2c9999e2d5b8c216d4f751e7e91c0a0d6d",
          "sha256": "1eef57a0daf128fd9a236af482e1b78263e344b81a655e075361911a815936b4",
          "sha1": "4818c9569e83e6dff50a1ab0f1d1519ea78777da",
          "md5": "09d8595c82f413260ec0cbebfb2e7601"
        }
      ]
    }
  ]
}
