{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_release",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.8.aar",
          "url": "trust_vision_plugin_release-1.8.aar",
          "size": 74657,
          "sha512": "0028fb95c32cae56e90ddd1887e6bcc3d952ab6583155d987e6728fddc933f40c20ef8cd5218392ac060072713513393f28509df38449d397d7ec2a14816e8b9",
          "sha256": "e807c1af28f62db53fca402ce90972bffe9b05f3337655a3a8b01412eae4a8ef",
          "sha1": "99607d1c88ea0b7696e767704fe37b33d6c301af",
          "md5": "3f7223a3a9ff8fb2de71f92f8f1f1564"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.8.aar",
          "url": "trust_vision_plugin_release-1.8.aar",
          "size": 74657,
          "sha512": "0028fb95c32cae56e90ddd1887e6bcc3d952ab6583155d987e6728fddc933f40c20ef8cd5218392ac060072713513393f28509df38449d397d7ec2a14816e8b9",
          "sha256": "e807c1af28f62db53fca402ce90972bffe9b05f3337655a3a8b01412eae4a8ef",
          "sha1": "99607d1c88ea0b7696e767704fe37b33d6c301af",
          "md5": "3f7223a3a9ff8fb2de71f92f8f1f1564"
        }
      ]
    }
  ]
}
