{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linkid.flutter_linkid_digitalfootprint",
    "module": "flutter_linkid_digitalfootprint_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_linkid_digitalfootprint_release-1.0.aar",
          "url": "flutter_linkid_digitalfootprint_release-1.0.aar",
          "size": 5541,
          "sha512": "23acf29471e48c1a00e1ef4c5d911b1afaaba53004728a2743d765062cbd73591a89e63fc098fbeeb9b1cf2b78046140f69ce50dc4746c0282d77897bbea3dea",
          "sha256": "8fe48c7489064a7a09f404aa0041e06a5512ed7d13849ef4854015535bd42488",
          "sha1": "1d70b6ff9eb4a75bfeb664bdb354c8ba9bd4b24f",
          "md5": "ce19ce8cdf52ef50274925a486c7a6a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.linkid.digitalfootprint",
          "module": "linkid-digitalfootprint",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "fr.bmartel",
          "module": "jspeedtest",
          "version": {
            "requires": "1.32.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_linkid_digitalfootprint_release-1.0.aar",
          "url": "flutter_linkid_digitalfootprint_release-1.0.aar",
          "size": 5541,
          "sha512": "23acf29471e48c1a00e1ef4c5d911b1afaaba53004728a2743d765062cbd73591a89e63fc098fbeeb9b1cf2b78046140f69ce50dc4746c0282d77897bbea3dea",
          "sha256": "8fe48c7489064a7a09f404aa0041e06a5512ed7d13849ef4854015535bd42488",
          "sha1": "1d70b6ff9eb4a75bfeb664bdb354c8ba9bd4b24f",
          "md5": "ce19ce8cdf52ef50274925a486c7a6a5"
        }
      ]
    }
  ]
}
