{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.0.0.aar",
          "url": "ekyc_flutter_sdk_release-1.0.0.aar",
          "size": 8140729,
          "sha512": "3fae1f11c70879d30265d0912aa0b7bee6c7bc375d9fdcf78387975ee4e569d5296d310e104b180f5b07c7741929311d4f09e334c5782c3adc9e384b68e206d0",
          "sha256": "a33b10d37621635c1857a530e56b34cc9bfdcc10af407c62b111d8184045cd8e",
          "sha1": "f3b203990882424d15c35b107ec8ecc4e361bcc0",
          "md5": "ad9006e325f4d8fc41f0187e5c836bc2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.0.0.aar",
          "url": "ekyc_flutter_sdk_release-1.0.0.aar",
          "size": 8140729,
          "sha512": "3fae1f11c70879d30265d0912aa0b7bee6c7bc375d9fdcf78387975ee4e569d5296d310e104b180f5b07c7741929311d4f09e334c5782c3adc9e384b68e206d0",
          "sha256": "a33b10d37621635c1857a530e56b34cc9bfdcc10af407c62b111d8184045cd8e",
          "sha1": "f3b203990882424d15c35b107ec8ecc4e361bcc0",
          "md5": "ad9006e325f4d8fc41f0187e5c836bc2"
        }
      ]
    }
  ]
}
