{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.0.aar",
          "url": "ekyc_flutter_sdk_debug-1.0.aar",
          "size": 8140960,
          "sha512": "42d709521e4594ad1cdf1570f6a50e6e0579c3489d1f158d90696f130bfa00bbe1549d352f3bf3aa820ded854941a4754c28d1d1dfb44324eba367c63a0cc359",
          "sha256": "c9f8843de04182f008987267ea4a450770e393c5c0aa744fc380851150b83c01",
          "sha1": "73b569f55bbdaa099c6e3e9159ee946738fbfa16",
          "md5": "7059e1c9ad6d3cd460fdb7260e74685b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.0.aar",
          "url": "ekyc_flutter_sdk_debug-1.0.aar",
          "size": 8140960,
          "sha512": "42d709521e4594ad1cdf1570f6a50e6e0579c3489d1f158d90696f130bfa00bbe1549d352f3bf3aa820ded854941a4754c28d1d1dfb44324eba367c63a0cc359",
          "sha256": "c9f8843de04182f008987267ea4a450770e393c5c0aa744fc380851150b83c01",
          "sha1": "73b569f55bbdaa099c6e3e9159ee946738fbfa16",
          "md5": "7059e1c9ad6d3cd460fdb7260e74685b"
        }
      ]
    }
  ]
}
