{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_debug",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.1.aar",
          "url": "ekyc_flutter_sdk_debug-1.1.aar",
          "size": 8140971,
          "sha512": "89e7c7563ed7f25a3df3cd93d6ff49d146f80b6430041f5f2ab39e6385c5d6add7fb829ab01c81b67a9180416082c9dfee9876b102fb9e8b45b51974e4a06f5a",
          "sha256": "a07851d7458d78005e34d37ef317ecc14e5a6ef79c79907bc65f79378265a328",
          "sha1": "0562db820ffdcc87a3b15778e8ca386e2758db55",
          "md5": "0c05901c953488e5c3c03adea31f3b34"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.1.aar",
          "url": "ekyc_flutter_sdk_debug-1.1.aar",
          "size": 8140971,
          "sha512": "89e7c7563ed7f25a3df3cd93d6ff49d146f80b6430041f5f2ab39e6385c5d6add7fb829ab01c81b67a9180416082c9dfee9876b102fb9e8b45b51974e4a06f5a",
          "sha256": "a07851d7458d78005e34d37ef317ecc14e5a6ef79c79907bc65f79378265a328",
          "sha1": "0562db820ffdcc87a3b15778e8ca386e2758db55",
          "md5": "0c05901c953488e5c3c03adea31f3b34"
        }
      ]
    }
  ]
}
