{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 21462,
          "sha512": "28f6e0960c13a1d975a6ce95687db7c8defd9d2ba936b985152848eeb4603ee0804adf8676a4dfd1f6469fc0b579877eeb290da459ebad8935ff14b2e53b2d36",
          "sha256": "d33ee7b01b357639e72c64a67dc1893e97c5ecef151ef66e91472095bc923342",
          "sha1": "fe9f9078976cff4fc750ae65a72435dc10c23fae",
          "md5": "c61846087f1df0aff91f0a5c99044148"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 21462,
          "sha512": "28f6e0960c13a1d975a6ce95687db7c8defd9d2ba936b985152848eeb4603ee0804adf8676a4dfd1f6469fc0b579877eeb290da459ebad8935ff14b2e53b2d36",
          "sha256": "d33ee7b01b357639e72c64a67dc1893e97c5ecef151ef66e91472095bc923342",
          "sha1": "fe9f9078976cff4fc750ae65a72435dc10c23fae",
          "md5": "c61846087f1df0aff91f0a5c99044148"
        }
      ]
    }
  ]
}
