{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 20956,
          "sha512": "0e927569c0cf25976935ec34c8db977abde3e3e0e69581f04b08175d291bc538dca5e9e7eb586d3e1ea7d431ec2d32d524efe53c89c66d78248febdfefc92f1b",
          "sha256": "56d4b974a6a020f61fcac66094a80dbf0229b1926aacc4f7a70603deb3579dd6",
          "sha1": "863cf72ddd9f9fe758dc36695dff4630ee7b42aa",
          "md5": "26ec45969efaa4a1595aebd1aec355c2"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.aar",
          "url": "url_launcher_android_profile-1.0.aar",
          "size": 20956,
          "sha512": "0e927569c0cf25976935ec34c8db977abde3e3e0e69581f04b08175d291bc538dca5e9e7eb586d3e1ea7d431ec2d32d524efe53c89c66d78248febdfefc92f1b",
          "sha256": "56d4b974a6a020f61fcac66094a80dbf0229b1926aacc4f7a70603deb3579dd6",
          "sha1": "863cf72ddd9f9fe758dc36695dff4630ee7b42aa",
          "md5": "26ec45969efaa4a1595aebd1aec355c2"
        }
      ]
    }
  ]
}
