{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_debug",
    "version": "1.9.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.9.18.aar",
          "url": "ekyc_flutter_sdk_debug-1.9.18.aar",
          "size": 8140962,
          "sha512": "1bd61df978bd3c6fee93f7d2a7e338cc59e5253926ff9e31c82d01790ac1b8727ffe7baa82fe8cfce6aa71677e0813f2dfe33ae24969f6222ffb3845ad05efa9",
          "sha256": "5eb031a9734728a5713e1ea6b03858fd71f44b778a1cd12a3c2a8f3d86285045",
          "sha1": "b002f8763d03ca2b47945ffc7405927f7939654f",
          "md5": "596a9e6c743fe4839425d4840b5d7049"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "1.9.18"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.9.18.aar",
          "url": "ekyc_flutter_sdk_debug-1.9.18.aar",
          "size": 8140962,
          "sha512": "1bd61df978bd3c6fee93f7d2a7e338cc59e5253926ff9e31c82d01790ac1b8727ffe7baa82fe8cfce6aa71677e0813f2dfe33ae24969f6222ffb3845ad05efa9",
          "sha256": "5eb031a9734728a5713e1ea6b03858fd71f44b778a1cd12a3c2a8f3d86285045",
          "sha1": "b002f8763d03ca2b47945ffc7405927f7939654f",
          "md5": "596a9e6c743fe4839425d4840b5d7049"
        }
      ]
    }
  ]
}
