{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_release",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.1.aar",
          "url": "flutter_release-1.9.1.aar",
          "size": 18868453,
          "sha512": "d3e936c1a04d2423ea6463f96a85c397087dd412f066d8ee18bb22a9b238338ebb8abc1427215c9642825f803f9d7b3c7464c2f2557529c7264d9797c9a55efc",
          "sha256": "549350935d03dffd78e3f7aff6af586f5655e9d11a99646505d2dca657affc2d",
          "sha1": "16c928be0d4d19eb6fb5164b9c89afd1791c8e93",
          "md5": "7d50c2c500621f9668b6d918901ec13d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.1.aar",
          "url": "flutter_release-1.9.1.aar",
          "size": 18868453,
          "sha512": "d3e936c1a04d2423ea6463f96a85c397087dd412f066d8ee18bb22a9b238338ebb8abc1427215c9642825f803f9d7b3c7464c2f2557529c7264d9797c9a55efc",
          "sha256": "549350935d03dffd78e3f7aff6af586f5655e9d11a99646505d2dca657affc2d",
          "sha1": "16c928be0d4d19eb6fb5164b9c89afd1791c8e93",
          "md5": "7d50c2c500621f9668b6d918901ec13d"
        }
      ]
    }
  ]
}
