{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_debug",
    "version": "1.9.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.9.30.aar",
          "url": "trust_vision_plugin_debug-1.9.30.aar",
          "size": 72498,
          "sha512": "f085f32cd7cfdb1874a55cf2e1ce554b660be166c5034f746259aff9d6862687e16009f6813e0503cd8185106a3305608d5bb26031f0d2f31a3bbaf7e90a74a0",
          "sha256": "e6e0eea25dbf22b0bab94b696b2cfd4f08a14199a08e5523af1e5599af98de63",
          "sha1": "e49cffd9fe56f43015733648e4c96dc6c533d582",
          "md5": "587e2ee4f45ddd61a73fbc8d129301dd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.9.30.aar",
          "url": "trust_vision_plugin_debug-1.9.30.aar",
          "size": 72498,
          "sha512": "f085f32cd7cfdb1874a55cf2e1ce554b660be166c5034f746259aff9d6862687e16009f6813e0503cd8185106a3305608d5bb26031f0d2f31a3bbaf7e90a74a0",
          "sha256": "e6e0eea25dbf22b0bab94b696b2cfd4f08a14199a08e5523af1e5599af98de63",
          "sha1": "e49cffd9fe56f43015733648e4c96dc6c533d582",
          "md5": "587e2ee4f45ddd61a73fbc8d129301dd"
        }
      ]
    }
  ]
}
