{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_debug",
    "version": "release_28_oct_2023_v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-release_28_oct_2023_v5.aar",
          "url": "ekyc_flutter_sdk_debug-release_28_oct_2023_v5.aar",
          "size": 8140961,
          "sha512": "e89956f3ccf3507d5984706fa61c1a160b0713b90946fa1ecab9f3ef696f2328b4adb80809e29cd9b6213579ffc1f250a68b81a116abefa5c4d53d8553b5c34d",
          "sha256": "7b4fec00ca1bb4ba2d3ea3917471f0e542998bb48f8353daa9cb88bccf384e9b",
          "sha1": "13a92d52475754932e6876748a77d1bba946bfce",
          "md5": "d01de4b81ff821d19758177f55f606d6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "release_28_oct_2023_v5"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_debug",
          "version": {
            "requires": "release_28_oct_2023_v5"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-release_28_oct_2023_v5.aar",
          "url": "ekyc_flutter_sdk_debug-release_28_oct_2023_v5.aar",
          "size": 8140961,
          "sha512": "e89956f3ccf3507d5984706fa61c1a160b0713b90946fa1ecab9f3ef696f2328b4adb80809e29cd9b6213579ffc1f250a68b81a116abefa5c4d53d8553b5c34d",
          "sha256": "7b4fec00ca1bb4ba2d3ea3917471f0e542998bb48f8353daa9cb88bccf384e9b",
          "sha1": "13a92d52475754932e6876748a77d1bba946bfce",
          "md5": "d01de4b81ff821d19758177f55f606d6"
        }
      ]
    }
  ]
}
