{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_debug",
    "version": "1.9.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.9.18.aar",
          "url": "trust_vision_plugin_debug-1.9.18.aar",
          "size": 72501,
          "sha512": "25d93c3afc58d5a554391455d8fd90b0d4897c570192cac5ad61db67bd569c7e922fdd27112ea36b2f5e7e8b7de07d42d21ac16fb16de7dcb10defff7dc664c4",
          "sha256": "eff04d9b577f56b4a5be5f5ae076bf3ec3ab3195e2f8145bcee08fea618dbf4e",
          "sha1": "27fcc1d8039b86e9444a58fdb33c50594f0f1204",
          "md5": "cfa13db10f8fb6701239bf1bb3de12f8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.9.18.aar",
          "url": "trust_vision_plugin_debug-1.9.18.aar",
          "size": 72501,
          "sha512": "25d93c3afc58d5a554391455d8fd90b0d4897c570192cac5ad61db67bd569c7e922fdd27112ea36b2f5e7e8b7de07d42d21ac16fb16de7dcb10defff7dc664c4",
          "sha256": "eff04d9b577f56b4a5be5f5ae076bf3ec3ab3195e2f8145bcee08fea618dbf4e",
          "sha1": "27fcc1d8039b86e9444a58fdb33c50594f0f1204",
          "md5": "cfa13db10f8fb6701239bf1bb3de12f8"
        }
      ]
    }
  ]
}
