{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linkid.flutter_linkid_digitalfootprint",
    "module": "flutter_linkid_digitalfootprint_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_linkid_digitalfootprint_profile-1.0.aar",
          "url": "flutter_linkid_digitalfootprint_profile-1.0.aar",
          "size": 5626,
          "sha512": "344a60e2c819ee4e2d260937253fcb7bfebc02e8671335c25332efd880ddd58d657d34302c625e3385407236b9f25c78c4439d614cfe0c38208e47f1b9952b64",
          "sha256": "25a00d0f59bda2cfff0a932bd211656aef660b9f254785d14a929410c7069bce",
          "sha1": "ace1c8fa26d0b1c94dfa6b4a88ebcaed17642645",
          "md5": "4427c89c755e8e1703f2859978245ee6"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.linkid.digitalfootprint",
          "module": "linkid-digitalfootprint",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "fr.bmartel",
          "module": "jspeedtest",
          "version": {
            "requires": "1.32.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_linkid_digitalfootprint_profile-1.0.aar",
          "url": "flutter_linkid_digitalfootprint_profile-1.0.aar",
          "size": 5626,
          "sha512": "344a60e2c819ee4e2d260937253fcb7bfebc02e8671335c25332efd880ddd58d657d34302c625e3385407236b9f25c78c4439d614cfe0c38208e47f1b9952b64",
          "sha256": "25a00d0f59bda2cfff0a932bd211656aef660b9f254785d14a929410c7069bce",
          "sha1": "ace1c8fa26d0b1c94dfa6b4a88ebcaed17642645",
          "md5": "4427c89c755e8e1703f2859978245ee6"
        }
      ]
    }
  ]
}
