{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.9.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.9.20.aar",
          "url": "url_launcher_android_release-1.9.20.aar",
          "size": 23292,
          "sha512": "2c9331c7e75f4efb1f462963c432859c6aaf0bbf595f994c5876645a9a84b7a2a4de4796e7706ef3a556e8cff3eca4abd5c8016a5ed927fabd7a366f1e88f673",
          "sha256": "d33c0c4a74dbef5bbc9177505008b3d2c34bb0c466867596037a19a5a89a99cb",
          "sha1": "85055d83b0a38512e158d53ef22c0120f05127d7",
          "md5": "73f70bc501341b1b27b9c7d7416bfe10"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.9.20.aar",
          "url": "url_launcher_android_release-1.9.20.aar",
          "size": 23292,
          "sha512": "2c9331c7e75f4efb1f462963c432859c6aaf0bbf595f994c5876645a9a84b7a2a4de4796e7706ef3a556e8cff3eca4abd5c8016a5ed927fabd7a366f1e88f673",
          "sha256": "d33c0c4a74dbef5bbc9177505008b3d2c34bb0c466867596037a19a5a89a99cb",
          "sha1": "85055d83b0a38512e158d53ef22c0120f05127d7",
          "md5": "73f70bc501341b1b27b9c7d7416bfe10"
        }
      ]
    }
  ]
}
