{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "release_28_oct_2023_v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-release_28_oct_2023_v5.aar",
          "url": "share_plus_debug-release_28_oct_2023_v5.aar",
          "size": 22227,
          "sha512": "e8d83053758c5e0acfc93a2fcacf79d285e602b86d0c098b0a462eeb1d5e812c8b6c3da46acf3970e8015acb93aafca9d7e52df24df8b2d151aeb226421f35bc",
          "sha256": "c0f8b764960265a6f4d6401268c6ff08f1e5e573bc9cd9b5db3e9e406e9b8ac4",
          "sha1": "59ef7a77276b3918054c0c5b19886f63cef3caa9",
          "md5": "bf3234024ad98ac54a098b372b7b4175"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-release_28_oct_2023_v5.aar",
          "url": "share_plus_debug-release_28_oct_2023_v5.aar",
          "size": 22227,
          "sha512": "e8d83053758c5e0acfc93a2fcacf79d285e602b86d0c098b0a462eeb1d5e812c8b6c3da46acf3970e8015acb93aafca9d7e52df24df8b2d151aeb226421f35bc",
          "sha256": "c0f8b764960265a6f4d6401268c6ff08f1e5e573bc9cd9b5db3e9e406e9b8ac4",
          "sha1": "59ef7a77276b3918054c0c5b19886f63cef3caa9",
          "md5": "bf3234024ad98ac54a098b372b7b4175"
        }
      ]
    }
  ]
}
