{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-release_28_oct_2023_v4.aar",
          "url": "share_plus_release-release_28_oct_2023_v4.aar",
          "size": 21343,
          "sha512": "0ac82ce078bbd8308d1d90871946b562fbc3ab1c579941a718edd7c4e03aeb77280610f7cab06bdcf307fbe0f6e642f5f209e1e2dfcf188bcb80a3576fa823e3",
          "sha256": "a5e23068079d4133a3d203b7d582ec6e1eb64d7a42c27b4df16da127e7ab634f",
          "sha1": "188e8527b11511a5099ce05fd12745af55ea1fe8",
          "md5": "d90d2e832fc694557a51a1b6cdd29f1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-release_28_oct_2023_v4.aar",
          "url": "share_plus_release-release_28_oct_2023_v4.aar",
          "size": 21343,
          "sha512": "0ac82ce078bbd8308d1d90871946b562fbc3ab1c579941a718edd7c4e03aeb77280610f7cab06bdcf307fbe0f6e642f5f209e1e2dfcf188bcb80a3576fa823e3",
          "sha256": "a5e23068079d4133a3d203b7d582ec6e1eb64d7a42c27b4df16da127e7ab634f",
          "sha1": "188e8527b11511a5099ce05fd12745af55ea1fe8",
          "md5": "d90d2e832fc694557a51a1b6cdd29f1e"
        }
      ]
    }
  ]
}
