{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_release",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.github.florent37.assetsaudioplayer",
          "module": "assets_audio_player_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-release_28_oct_2023_v4.aar",
          "url": "flutter_release-release_28_oct_2023_v4.aar",
          "size": 20053171,
          "sha512": "d730c06cb098b6b080976a24147ebc0ee1dcb833c5b3c888e84e639444d7252fe9211a65c314af1e403cbffdebb6f229d08e85a3408b006bc7255edda493852e",
          "sha256": "5ea9dc0ee67af6775741c2110aca0405a48a2c13c1ba48209b799f073f3ead3a",
          "sha1": "705cdbccd8e9b830059a5bc1f51713c205cde81f",
          "md5": "6fc1a36b2d9f35f3d8d3103154992db3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.github.florent37.assetsaudioplayer",
          "module": "assets_audio_player_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-release_28_oct_2023_v4.aar",
          "url": "flutter_release-release_28_oct_2023_v4.aar",
          "size": 20053171,
          "sha512": "d730c06cb098b6b080976a24147ebc0ee1dcb833c5b3c888e84e639444d7252fe9211a65c314af1e403cbffdebb6f229d08e85a3408b006bc7255edda493852e",
          "sha256": "5ea9dc0ee67af6775741c2110aca0405a48a2c13c1ba48209b799f073f3ead3a",
          "sha1": "705cdbccd8e9b830059a5bc1f51713c205cde81f",
          "md5": "6fc1a36b2d9f35f3d8d3103154992db3"
        }
      ]
    }
  ]
}
