{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.1.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.1.aar",
          "size": 4765,
          "sha512": "62e844108af7b265df573e1a035a5a96b5bc9d2479b1a755b5bff219483db68256d5fbb8f4938b95b6373365dbcb8e8b7751fac46d93f1c78122a62d5fc1ba0d",
          "sha256": "ba17486ccd94f7de4de23ab2c2666fa1bed5037c3141fb55092f2f6cb4b65eb1",
          "sha1": "e804938cd727867849ab0451f8ccc8f703165d86",
          "md5": "12466b0b9c800c5beadf4e3c0c97f978"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.1.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.1.aar",
          "size": 4765,
          "sha512": "62e844108af7b265df573e1a035a5a96b5bc9d2479b1a755b5bff219483db68256d5fbb8f4938b95b6373365dbcb8e8b7751fac46d93f1c78122a62d5fc1ba0d",
          "sha256": "ba17486ccd94f7de4de23ab2c2666fa1bed5037c3141fb55092f2f6cb4b65eb1",
          "sha1": "e804938cd727867849ab0451f8ccc8f703165d86",
          "md5": "12466b0b9c800c5beadf4e3c0c97f978"
        }
      ]
    }
  ]
}
