{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_debug",
    "version": "release_28_oct_2023_v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "camera_debug-release_28_oct_2023_v5.aar",
          "url": "camera_debug-release_28_oct_2023_v5.aar",
          "size": 109673,
          "sha512": "1b65a5a18a2194fbcad768555bffb8a63b6bdbd24a9f757a10c8dced95d95bf896d445d85bda1be28ce9aa95bde8e2174cfd9e5b73f8b288d6b1faf55a6b3954",
          "sha256": "c10ce17537b5111bcef3fafb36ce54c0379e94dfaa05e81d112b5ad6e80c0f30",
          "sha1": "682912c33113fc36517b03ad8bd68f26a6b4843b",
          "md5": "d03a299cbb136d8cfbf7f01dfeace899"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "release_28_oct_2023_v5"
          }
        }
      ],
      "files": [
        {
          "name": "camera_debug-release_28_oct_2023_v5.aar",
          "url": "camera_debug-release_28_oct_2023_v5.aar",
          "size": 109673,
          "sha512": "1b65a5a18a2194fbcad768555bffb8a63b6bdbd24a9f757a10c8dced95d95bf896d445d85bda1be28ce9aa95bde8e2174cfd9e5b73f8b288d6b1faf55a6b3954",
          "sha256": "c10ce17537b5111bcef3fafb36ce54c0379e94dfaa05e81d112b5ad6e80c0f30",
          "sha1": "682912c33113fc36517b03ad8bd68f26a6b4843b",
          "md5": "d03a299cbb136d8cfbf7f01dfeace899"
        }
      ]
    }
  ]
}
