{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_release",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.2.aar",
          "url": "flutter_release-1.9.2.aar",
          "size": 18865280,
          "sha512": "74e62b640e61740fb90e43b23f1bd01c15297e1b1de1796762f50c4f0c608fc828bfe3fe79140816134698fd3008689c55f59739c24143894a26eaa5e1be8cbe",
          "sha256": "376609180f79a3fd630d1eaceaaa0d6d4c1430ccabc68e55da6b82d78ce48f5f",
          "sha1": "9bdf88d9b7c9b4e394bf9cde21e91f1a7142f9e9",
          "md5": "cd76722e7ca9bcda8b2dc23aebba5d46"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.2.aar",
          "url": "flutter_release-1.9.2.aar",
          "size": 18865280,
          "sha512": "74e62b640e61740fb90e43b23f1bd01c15297e1b1de1796762f50c4f0c608fc828bfe3fe79140816134698fd3008689c55f59739c24143894a26eaa5e1be8cbe",
          "sha256": "376609180f79a3fd630d1eaceaaa0d6d4c1430ccabc68e55da6b82d78ce48f5f",
          "sha1": "9bdf88d9b7c9b4e394bf9cde21e91f1a7142f9e9",
          "md5": "cd76722e7ca9bcda8b2dc23aebba5d46"
        }
      ]
    }
  ]
}
