{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.9.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.9.18.aar",
          "url": "url_launcher_android_debug-1.9.18.aar",
          "size": 24493,
          "sha512": "77155e27a3468d29e6e5d06480ddfef329a11034b6b3a64157b1f5cdb164ba28e90ad133f82c775022e4689f0fb77d25b6687e85bf83138d3a38c67a2c347953",
          "sha256": "313356221cc121ae2c522246305130c94af486375e7835c8e6157f4bcef20161",
          "sha1": "73d4bde1c359b9f7b93fec4a00c6e216313920b4",
          "md5": "c8b58620c04c116ce4a01771e7ff8416"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.9.18.aar",
          "url": "url_launcher_android_debug-1.9.18.aar",
          "size": 24493,
          "sha512": "77155e27a3468d29e6e5d06480ddfef329a11034b6b3a64157b1f5cdb164ba28e90ad133f82c775022e4689f0fb77d25b6687e85bf83138d3a38c67a2c347953",
          "sha256": "313356221cc121ae2c522246305130c94af486375e7835c8e6157f4bcef20161",
          "sha1": "73d4bde1c359b9f7b93fec4a00c6e216313920b4",
          "md5": "c8b58620c04c116ce4a01771e7ff8416"
        }
      ]
    }
  ]
}
