{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_release",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.1.aar",
          "url": "trust_vision_plugin_release-1.1.aar",
          "size": 74641,
          "sha512": "5e5a5ba61486465ca0b98d40985d15460557d180e703a967d837fa9317189a81874f0a37fc7ad1d785bfd991f271a37cf2b3377021f6b78bb6cf0a15e326cfb9",
          "sha256": "889f2a3cbb51a782ac9a19a490b2c33787e95ffa48b47f5b80ac417b18fcc30b",
          "sha1": "af4cf77a6379cc091744c4d606d0f34c863a499e",
          "md5": "a93d94297ffebdfce5bd8d77f80f8bf8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.1.aar",
          "url": "trust_vision_plugin_release-1.1.aar",
          "size": 74641,
          "sha512": "5e5a5ba61486465ca0b98d40985d15460557d180e703a967d837fa9317189a81874f0a37fc7ad1d785bfd991f271a37cf2b3377021f6b78bb6cf0a15e326cfb9",
          "sha256": "889f2a3cbb51a782ac9a19a490b2c33787e95ffa48b47f5b80ac417b18fcc30b",
          "sha1": "af4cf77a6379cc091744c4d606d0f34c863a499e",
          "md5": "a93d94297ffebdfce5bd8d77f80f8bf8"
        }
      ]
    }
  ]
}
