{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_profile-1.0.aar",
          "url": "ekyc_flutter_sdk_profile-1.0.aar",
          "size": 8140727,
          "sha512": "f2da8d26b10d142a787d454504f6dd4de6a5d0ba67737b4150a2bd5dcef40247748b375d825b9dbdea9b9e1c99b65e31892de55e29ddeade84f6790f9aa42474",
          "sha256": "81db30ef38ecc27f6ed28fba2099699ebf194bc9d23a6df66950bf0b5f5f38e5",
          "sha1": "f04c1b0d1220eb0731f1f730b83cbade3fb68283",
          "md5": "10349e387b987170d34641c993deae15"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_profile-1.0.aar",
          "url": "ekyc_flutter_sdk_profile-1.0.aar",
          "size": 8140727,
          "sha512": "f2da8d26b10d142a787d454504f6dd4de6a5d0ba67737b4150a2bd5dcef40247748b375d825b9dbdea9b9e1c99b65e31892de55e29ddeade84f6790f9aa42474",
          "sha256": "81db30ef38ecc27f6ed28fba2099699ebf194bc9d23a6df66950bf0b5f5f38e5",
          "sha1": "f04c1b0d1220eb0731f1f730b83cbade3fb68283",
          "md5": "10349e387b987170d34641c993deae15"
        }
      ]
    }
  ]
}
