{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.cake.ekyc.sdk.eid",
    "module": "cake_eid_release",
    "version": "1.9.76",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "cake_eid_release-1.9.76.aar",
          "url": "cake_eid_release-1.9.76.aar",
          "size": 11324,
          "sha512": "cb56c7ab676d15dd3631be27ff5c237d68ea6628ffa6bf34caaba36481c785e8b1fa1bd923921059aa22e8b7db22a7dcc76b861a696f0eb767f57cbfffbe82a1",
          "sha256": "29fae93eeb33ac5a83daadb19cef5df0c6a92a248545ff7029a991bfa813b8bf",
          "sha1": "aad3ea63fb1ea143c2913675517449ae86632bf8",
          "md5": "e728ac9ff6714f93f3b2dd7757cb70e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "vn.cake.ekyc.sdk",
          "module": "eid",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "cake_eid_release-1.9.76.aar",
          "url": "cake_eid_release-1.9.76.aar",
          "size": 11324,
          "sha512": "cb56c7ab676d15dd3631be27ff5c237d68ea6628ffa6bf34caaba36481c785e8b1fa1bd923921059aa22e8b7db22a7dcc76b861a696f0eb767f57cbfffbe82a1",
          "sha256": "29fae93eeb33ac5a83daadb19cef5df0c6a92a248545ff7029a991bfa813b8bf",
          "sha1": "aad3ea63fb1ea143c2913675517449ae86632bf8",
          "md5": "e728ac9ff6714f93f3b2dd7757cb70e9"
        }
      ]
    }
  ]
}
