{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_debug",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "camera_debug-release_28_oct_2023_v4.aar",
          "url": "camera_debug-release_28_oct_2023_v4.aar",
          "size": 107888,
          "sha512": "560cd46834c1328c529557b48b93540298a511358e33c265edc17fcdb135bad98d56ec06581a383da47d606bde01b8a1a0982a74700e2132a6a3f6e57535728b",
          "sha256": "6616884d8cbfb6c9cbfed8722e078684bab0ae74132b5fedd27fff277813410c",
          "sha1": "0e993115b0fe13fcab42f49db96791d701780c05",
          "md5": "17dce2c32df233b9ee3054b2c03edb69"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        }
      ],
      "files": [
        {
          "name": "camera_debug-release_28_oct_2023_v4.aar",
          "url": "camera_debug-release_28_oct_2023_v4.aar",
          "size": 107888,
          "sha512": "560cd46834c1328c529557b48b93540298a511358e33c265edc17fcdb135bad98d56ec06581a383da47d606bde01b8a1a0982a74700e2132a6a3f6e57535728b",
          "sha256": "6616884d8cbfb6c9cbfed8722e078684bab0ae74132b5fedd27fff277813410c",
          "sha1": "0e993115b0fe13fcab42f49db96791d701780c05",
          "md5": "17dce2c32df233b9ee3054b2c03edb69"
        }
      ]
    }
  ]
}
