{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.8.aar",
          "url": "url_launcher_android_release-1.8.aar",
          "size": 21458,
          "sha512": "4b86662a3bb215209c92d517d484f972b678c9dfc355622836575f143e19cabc64fd7315d28a11d423c6bf67635d2b31df3ec6cba9866bb1c6c3bac029414a12",
          "sha256": "2f55cdf847136fb173a853f4fb15db712a09e727ab908cbdcebb6908fd98ee5b",
          "sha1": "8ec71b1b7fece5d7643bc84c2dff817b5a79b35c",
          "md5": "5f8da2e989752755f9f34edd1bfcba51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a794cf2681c6c9fe7b260e0e84de96298dc9c18b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.8.aar",
          "url": "url_launcher_android_release-1.8.aar",
          "size": 21458,
          "sha512": "4b86662a3bb215209c92d517d484f972b678c9dfc355622836575f143e19cabc64fd7315d28a11d423c6bf67635d2b31df3ec6cba9866bb1c6c3bac029414a12",
          "sha256": "2f55cdf847136fb173a853f4fb15db712a09e727ab908cbdcebb6908fd98ee5b",
          "sha1": "8ec71b1b7fece5d7643bc84c2dff817b5a79b35c",
          "md5": "5f8da2e989752755f9f34edd1bfcba51"
        }
      ]
    }
  ]
}
