{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_debug",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.8.aar",
          "url": "ekyc_flutter_sdk_debug-1.8.aar",
          "size": 8140958,
          "sha512": "78ad1aa825583747a63dad01d3a1d4078d53ff7f896e5545157eaa66782a7d81633a44c056e02b6c7462a9e2967a0d391dc35a9bf01d20196acc9de0f4d23d41",
          "sha256": "d7a6e7f15c761bc97805fcf50e1a778bade95335ae37b58112c4d1c15fb722a7",
          "sha1": "cef1f66e9b0ca1160356fc06ae2e4b01683e9ece",
          "md5": "77d2563da3350f3258f812a3e91c30d7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_debug",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_debug-1.8.aar",
          "url": "ekyc_flutter_sdk_debug-1.8.aar",
          "size": 8140958,
          "sha512": "78ad1aa825583747a63dad01d3a1d4078d53ff7f896e5545157eaa66782a7d81633a44c056e02b6c7462a9e2967a0d391dc35a9bf01d20196acc9de0f4d23d41",
          "sha256": "d7a6e7f15c761bc97805fcf50e1a778bade95335ae37b58112c4d1c15fb722a7",
          "sha1": "cef1f66e9b0ca1160356fc06ae2e4b01683e9ece",
          "md5": "77d2563da3350f3258f812a3e91c30d7"
        }
      ]
    }
  ]
}
