{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "size": 4936,
          "sha512": "3cdf2f375f106a4adc842ccc9e0ce61f0e3115101dc6dd275a022116976f51050396a0f201a7ab1ec25fe0fc123c65e023a6b40a1d5847e04dd910b8344458f0",
          "sha256": "af109fb3fc12d57582dce4c5ad335320346e16c1eee94aa03a2d5e8839cebda7",
          "sha1": "83c877922d38ee0245b1d5e29aabdc63b8db5f65",
          "md5": "3dbd4dda557b55692dcc97d55c96891f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "size": 4936,
          "sha512": "3cdf2f375f106a4adc842ccc9e0ce61f0e3115101dc6dd275a022116976f51050396a0f201a7ab1ec25fe0fc123c65e023a6b40a1d5847e04dd910b8344458f0",
          "sha256": "af109fb3fc12d57582dce4c5ad335320346e16c1eee94aa03a2d5e8839cebda7",
          "sha1": "83c877922d38ee0245b1d5e29aabdc63b8db5f65",
          "md5": "3dbd4dda557b55692dcc97d55c96891f"
        }
      ]
    }
  ]
}
