{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.0.aar",
          "url": "trust_vision_plugin_debug-1.0.aar",
          "size": 76208,
          "sha512": "0f0c94b29824075b16bc2cec09531182031316bb299d2c4609030de768f1867aa1676e274897de2d73f25d3b72d671f1b07470b837fa6df963075457c150076d",
          "sha256": "355116d1a611440ebd292104ae543538128ed5361b4386ccee06b443f52f1caf",
          "sha1": "339c2b5775ef5d224a14478b03aabc3f059bc320",
          "md5": "af40fbea66b3e8029601ab7ee0705297"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.2.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.0.aar",
          "url": "trust_vision_plugin_debug-1.0.aar",
          "size": 76208,
          "sha512": "0f0c94b29824075b16bc2cec09531182031316bb299d2c4609030de768f1867aa1676e274897de2d73f25d3b72d671f1b07470b837fa6df963075457c150076d",
          "sha256": "355116d1a611440ebd292104ae543538128ed5361b4386ccee06b443f52f1caf",
          "sha1": "339c2b5775ef5d224a14478b03aabc3f059bc320",
          "md5": "af40fbea66b3e8029601ab7ee0705297"
        }
      ]
    }
  ]
}
