{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.0.aar",
          "url": "trust_vision_plugin_debug-1.0.aar",
          "size": 76234,
          "sha512": "196869eb9dc152328ba2998f2dba0efac9e9c9ab4549009126a849658a7fc827a453becbc3115a2ee6eba50ef756828480e0ae6f603baa4ab504f81cbffb3119",
          "sha256": "fb1ee64ede45e5c00964cac07c13c34755fc1e08dc7ba7b0e4e1a7d134e12143",
          "sha1": "2b5e64acaf80078ec2402d61ea20c733309bfb22",
          "md5": "2fd92e099ee13a850e703e6f5dec2bfb"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.0.aar",
          "url": "trust_vision_plugin_debug-1.0.aar",
          "size": 76234,
          "sha512": "196869eb9dc152328ba2998f2dba0efac9e9c9ab4549009126a849658a7fc827a453becbc3115a2ee6eba50ef756828480e0ae6f603baa4ab504f81cbffb3119",
          "sha256": "fb1ee64ede45e5c00964cac07c13c34755fc1e08dc7ba7b0e4e1a7d134e12143",
          "sha1": "2b5e64acaf80078ec2402d61ea20c733309bfb22",
          "md5": "2fd92e099ee13a850e703e6f5dec2bfb"
        }
      ]
    }
  ]
}
