{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_debug",
    "version": "release_28_oct_2023_v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.github.florent37.assetsaudioplayer",
          "module": "assets_audio_player_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-release_28_oct_2023_v4.aar",
          "url": "flutter_debug-release_28_oct_2023_v4.aar",
          "size": 29269155,
          "sha512": "1d3d58888c274700e7f71ec531fc464942ff3749985df532f1700446babd38c88ae4e0fdf2d710f215c7ee5c00679fa0f3b5e34c03e571529843a1748a832cfb",
          "sha256": "f9002598240fb2bbad98453fd2141c3e9469e613e9809b9302758df38d42ea49",
          "sha1": "ae8cf74b610d1eca471f60307d170d8d20d3cf7b",
          "md5": "84c698215dbcc889c6c75f302510a00a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.github.florent37.assetsaudioplayer",
          "module": "assets_audio_player_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_debug",
          "version": {
            "requires": "release_28_oct_2023_v4"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-release_28_oct_2023_v4.aar",
          "url": "flutter_debug-release_28_oct_2023_v4.aar",
          "size": 29269155,
          "sha512": "1d3d58888c274700e7f71ec531fc464942ff3749985df532f1700446babd38c88ae4e0fdf2d710f215c7ee5c00679fa0f3b5e34c03e571529843a1748a832cfb",
          "sha256": "f9002598240fb2bbad98453fd2141c3e9469e613e9809b9302758df38d42ea49",
          "sha1": "ae8cf74b610d1eca471f60307d170d8d20d3cf7b",
          "md5": "84c698215dbcc889c6c75f302510a00a"
        }
      ]
    }
  ]
}
