{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.ekyc_flutter_sdk",
    "module": "ekyc_flutter_sdk_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.0.aar",
          "url": "ekyc_flutter_sdk_release-1.0.aar",
          "size": 8140730,
          "sha512": "84bd61ea90ca17a5a638bc1c10ba89b43aa72edd8eaff542585bf0f323668a18c1d86638e9f4145e92af482bbfaa73545a95dd5b68eaee0246cdfcc6dde9b1f0",
          "sha256": "8c9252932d6b3f1d2450f1c6b640b628e92f62793c2f558cd5ffda07fb8fbe57",
          "sha1": "6f0af2b1061c65b866def61742e93b68171e3741",
          "md5": "397ad406f478f23e58e4fc7e2977aad7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ekyc_flutter_sdk_release-1.0.aar",
          "url": "ekyc_flutter_sdk_release-1.0.aar",
          "size": 8140730,
          "sha512": "84bd61ea90ca17a5a638bc1c10ba89b43aa72edd8eaff542585bf0f323668a18c1d86638e9f4145e92af482bbfaa73545a95dd5b68eaee0246cdfcc6dde9b1f0",
          "sha256": "8c9252932d6b3f1d2450f1c6b640b628e92f62793c2f558cd5ffda07fb8fbe57",
          "sha1": "6f0af2b1061c65b866def61742e93b68171e3741",
          "md5": "397ad406f478f23e58e4fc7e2977aad7"
        }
      ]
    }
  ]
}
