{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_debug",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.1.aar",
          "url": "trust_vision_plugin_debug-1.1.aar",
          "size": 76222,
          "sha512": "cdc4af5b6315b32e4c15a30bcf5a3a2e06511503897ff0e4c87eb7a550f7bd0904edef31a739735fb80377db7482a16024f6aa3be221a7f4a24535e31e998bac",
          "sha256": "eef7e893e7f71597396aa32e6522a5339d8dd477f77910a84b823b562d9b1d21",
          "sha1": "880cf3ef912503f3a730c6818d90b93f1c1b8032",
          "md5": "4e1aa29a35803b6b6c75e606c56d1b63"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_debug-1.1.aar",
          "url": "trust_vision_plugin_debug-1.1.aar",
          "size": 76222,
          "sha512": "cdc4af5b6315b32e4c15a30bcf5a3a2e06511503897ff0e4c87eb7a550f7bd0904edef31a739735fb80377db7482a16024f6aa3be221a7f4a24535e31e998bac",
          "sha256": "eef7e893e7f71597396aa32e6522a5339d8dd477f77910a84b823b562d9b1d21",
          "sha1": "880cf3ef912503f3a730c6818d90b93f1c1b8032",
          "md5": "4e1aa29a35803b6b6c75e606c56d1b63"
        }
      ]
    }
  ]
}
