{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_release",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.aar",
          "url": "flutter_release-1.8.aar",
          "size": 18849509,
          "sha512": "fa8326369034d905487feae98f22ab9d353fcadf333d4cbb84c8afff61abd35ba7b3aeb1f865b381143e6a987e1779a36d0ce3869d2e9895cd4d9babed724c6d",
          "sha256": "f853e01f2038aa06fcdd5bd58761e3be268ddc156f53b4ad2077ae5d19677d1c",
          "sha1": "85350a355caf904d75bb71916dd36ea0624a2df8",
          "md5": "5586b49e02d6e0287f6784abd88fa425"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_release",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_release",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.aar",
          "url": "flutter_release-1.8.aar",
          "size": 18849509,
          "sha512": "fa8326369034d905487feae98f22ab9d353fcadf333d4cbb84c8afff61abd35ba7b3aeb1f865b381143e6a987e1779a36d0ce3869d2e9895cd4d9babed724c6d",
          "sha256": "f853e01f2038aa06fcdd5bd58761e3be268ddc156f53b4ad2077ae5d19677d1c",
          "sha1": "85350a355caf904d75bb71916dd36ea0624a2df8",
          "md5": "5586b49e02d6e0287f6784abd88fa425"
        }
      ]
    }
  ]
}
