{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.0.aar",
          "url": "trust_vision_plugin_release-1.0.aar",
          "size": 74653,
          "sha512": "bb5ef55ce8bfc59879bd55e4bea059b5adaac159fc757a32eebe3d88658e331cdd394a01772b3a7b03d2dce4d5161637b09e921dd130e7b16e00567eb02cc1b4",
          "sha256": "2a217e7f6290728de930aacbfac240a2aef5d02188f2221fd78ba42e0d57ad88",
          "sha1": "add5c6984f3c565628795152e31e2040ba0f02e5",
          "md5": "ccc68bb174c01d5fabc0dbdc52a3c24f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.0.aar",
          "url": "trust_vision_plugin_release-1.0.aar",
          "size": 74653,
          "sha512": "bb5ef55ce8bfc59879bd55e4bea059b5adaac159fc757a32eebe3d88658e331cdd394a01772b3a7b03d2dce4d5161637b09e921dd130e7b16e00567eb02cc1b4",
          "sha256": "2a217e7f6290728de930aacbfac240a2aef5d02188f2221fd78ba42e0d57ad88",
          "sha1": "add5c6984f3c565628795152e31e2040ba0f02e5",
          "md5": "ccc68bb174c01d5fabc0dbdc52a3c24f"
        }
      ]
    }
  ]
}
