{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_release",
    "version": "1.9.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.9.39.aar",
          "url": "trust_vision_plugin_release-1.9.39.aar",
          "size": 70997,
          "sha512": "0817317c6c19ac56f707034b01933571ec00ea743487a84962bf6e0a226552917f5996fa663456191630ba20ba4289391c36ec441618cc7ef6d0de77925dd11e",
          "sha256": "881704218cd8f8fdbe7eb80085cc3a8e3026033cab8606ce02c4dceae1e6d600",
          "sha1": "85100905760860da9acf0278bec62fcb9641d412",
          "md5": "399976f362dd11de1343758b5a2d6554"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_release-1.9.39.aar",
          "url": "trust_vision_plugin_release-1.9.39.aar",
          "size": 70997,
          "sha512": "0817317c6c19ac56f707034b01933571ec00ea743487a84962bf6e0a226552917f5996fa663456191630ba20ba4289391c36ec441618cc7ef6d0de77925dd11e",
          "sha256": "881704218cd8f8fdbe7eb80085cc3a8e3026033cab8606ce02c4dceae1e6d600",
          "sha1": "85100905760860da9acf0278bec62fcb9641d412",
          "md5": "399976f362dd11de1343758b5a2d6554"
        }
      ]
    }
  ]
}
