{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.florent37.assetsaudioplayer",
    "module": "assets_audio_player_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "assets_audio_player_profile-1.0.aar",
          "url": "assets_audio_player_profile-1.0.aar",
          "size": 191936,
          "sha512": "812a1e95ac3b2c70e9638d1a78b4c772d7322c026d9ce369eb8ca75a4f817ca00c0ec3cd898a0cd98df579e1bf9d1c6717a0e1a43b36db40d617982fb044de20",
          "sha256": "cfe0f37ba585bbbc13e6b088f8b915ad8fba191336d5410ebcafe0ef29674f0e",
          "sha1": "1db4c6725a2e44f3c5c04af9373b5313a8c31ba0",
          "md5": "67e2db14cc8395ef334c2e1892a91002"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.android.support",
          "module": "multidex",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "assets_audio_player_profile-1.0.aar",
          "url": "assets_audio_player_profile-1.0.aar",
          "size": 191936,
          "sha512": "812a1e95ac3b2c70e9638d1a78b4c772d7322c026d9ce369eb8ca75a4f817ca00c0ec3cd898a0cd98df579e1bf9d1c6717a0e1a43b36db40d617982fb044de20",
          "sha256": "cfe0f37ba585bbbc13e6b088f8b915ad8fba191336d5410ebcafe0ef29674f0e",
          "sha1": "1db4c6725a2e44f3c5c04af9373b5313a8c31ba0",
          "md5": "67e2db14cc8395ef334c2e1892a91002"
        }
      ]
    }
  ]
}
