{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.9.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.9.49.aar",
          "url": "device_info_plus_debug-1.9.49.aar",
          "size": 9836,
          "sha512": "45ae1cf1a50e053c4f3286cc22c073fe0f6fba31f684c938a38184b180e5006f33bd7657514215588004db93a615f509c709e128d45db3ffa39c645973835500",
          "sha256": "6759ec368806b80903b0212691b843385349d1a8925c99ace7c6d826b011a52b",
          "sha1": "e4827302521b7894831697864fb66d3ea0a215d0",
          "md5": "3613a724d4b4a446e3cd839c9d558fe8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.9.49.aar",
          "url": "device_info_plus_debug-1.9.49.aar",
          "size": 9836,
          "sha512": "45ae1cf1a50e053c4f3286cc22c073fe0f6fba31f684c938a38184b180e5006f33bd7657514215588004db93a615f509c709e128d45db3ffa39c645973835500",
          "sha256": "6759ec368806b80903b0212691b843385349d1a8925c99ace7c6d826b011a52b",
          "sha1": "e4827302521b7894831697864fb66d3ea0a215d0",
          "md5": "3613a724d4b4a446e3cd839c9d558fe8"
        }
      ]
    }
  ]
}
