{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.luan.audioplayers",
    "module": "audioplayers_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "audioplayers_android_profile-1.0.aar",
          "url": "audioplayers_android_profile-1.0.aar",
          "size": 59005,
          "sha512": "81edbac0773b44f1c793db4b98bc165732b2ff21e3194d6ce1fd17e0f81695090588e6d43f43559e9a9a3d65e05c85cea0f04b6000b74514afe82c3303d2f486",
          "sha256": "0b1a816a6cca5c16faf26d3694ca17ed019342494a256d6454b123e02fa2c513",
          "sha1": "a11118a9dcf31ae3495538a26fd357f405a20226",
          "md5": "f2ff80004d98f98c0607a1bcb4ad232a"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "audioplayers_android_profile-1.0.aar",
          "url": "audioplayers_android_profile-1.0.aar",
          "size": 59005,
          "sha512": "81edbac0773b44f1c793db4b98bc165732b2ff21e3194d6ce1fd17e0f81695090588e6d43f43559e9a9a3d65e05c85cea0f04b6000b74514afe82c3303d2f486",
          "sha256": "0b1a816a6cca5c16faf26d3694ca17ed019342494a256d6454b123e02fa2c513",
          "sha1": "a11118a9dcf31ae3495538a26fd357f405a20226",
          "md5": "f2ff80004d98f98c0607a1bcb4ad232a"
        }
      ]
    }
  ]
}
