{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uiux.ekyc",
    "module": "flutter_debug",
    "version": "1.9.27-pre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.9.27-pre.aar",
          "url": "flutter_debug-1.9.27-pre.aar",
          "size": 27680378,
          "sha512": "88c493b808c9914e04535a7a78e030d9427a909b92398e99be9aa6f77681ce52305164a83bbf166a1211e96bc42c43785728c29ae326e68956213c145fc4116d",
          "sha256": "21a9a47c28e3557edd755bd734dc47659dedb38e34986e96a95966ec8a27f864",
          "sha1": "51533cd35369f4fdbeec55e06cac71cc421abb5f",
          "md5": "e0c2627983e4dad47454c67da9ea9994"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3f3e560236539b7e2702f5ac790b2a4691b32d49"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "xyz.luan.audioplayers",
          "module": "audioplayers_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.tfliteflutter.tflite_flutter_plugin",
          "module": "tflite_flutter_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.linkid.flutter_linkid_digitalfootprint",
          "module": "flutter_linkid_digitalfootprint_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.juicy.juicy_score_flutter",
          "module": "juicy_score_flutter_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        },
        {
          "group": "com.example.ekyc_flutter_sdk",
          "module": "ekyc_flutter_sdk_debug",
          "version": {
            "requires": "1.9.27-pre"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.9.27-pre.aar",
          "url": "flutter_debug-1.9.27-pre.aar",
          "size": 27680378,
          "sha512": "88c493b808c9914e04535a7a78e030d9427a909b92398e99be9aa6f77681ce52305164a83bbf166a1211e96bc42c43785728c29ae326e68956213c145fc4116d",
          "sha256": "21a9a47c28e3557edd755bd734dc47659dedb38e34986e96a95966ec8a27f864",
          "sha1": "51533cd35369f4fdbeec55e06cac71cc421abb5f",
          "md5": "e0c2627983e4dad47454c67da9ea9994"
        }
      ]
    }
  ]
}
