{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 20955,
          "sha512": "5bd7bb1e4e77fa4b46684f2d784e32e906c6278a232dee3c36a593c30b84b68364b52c97efdac5f057ec6f6f23300ce44fc1b75bfa0b00d4d1870045cad82127",
          "sha256": "e28d49ea6766392cade66b6567fe274314d56f83c9e68f765c64352c03c5d873",
          "sha1": "a3276bc2329bdc3fad6836e092583d033d59ccdd",
          "md5": "e6857f3744cd16571b2cf06d85f86044"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 20955,
          "sha512": "5bd7bb1e4e77fa4b46684f2d784e32e906c6278a232dee3c36a593c30b84b68364b52c97efdac5f057ec6f6f23300ce44fc1b75bfa0b00d4d1870045cad82127",
          "sha256": "e28d49ea6766392cade66b6567fe274314d56f83c9e68f765c64352c03c5d873",
          "sha1": "a3276bc2329bdc3fad6836e092583d033d59ccdd",
          "md5": "e6857f3744cd16571b2cf06d85f86044"
        }
      ]
    }
  ]
}
