{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 23074,
          "sha512": "152a53106e035b64b56d099cbfe6c359c4f33bac27dba7a914a08563fcca0161f1e445aa39552b92e7252a55c2145ee278e7131c796da5a6a86f2e5670429f13",
          "sha256": "4b8c9e5fd787a8aaf85fecd2cc5ebb9d3569d8fe886eed0f505a1f3e04a3f7bb",
          "sha1": "77c19313c66c9c667661469eacb6289d0e38af91",
          "md5": "888d36d0296f45b7a834653151655b32"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 23074,
          "sha512": "152a53106e035b64b56d099cbfe6c359c4f33bac27dba7a914a08563fcca0161f1e445aa39552b92e7252a55c2145ee278e7131c796da5a6a86f2e5670429f13",
          "sha256": "4b8c9e5fd787a8aaf85fecd2cc5ebb9d3569d8fe886eed0f505a1f3e04a3f7bb",
          "sha1": "77c19313c66c9c667661469eacb6289d0e38af91",
          "md5": "888d36d0296f45b7a834653151655b32"
        }
      ]
    }
  ]
}
